"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { apiClient, ApiError } from "../../lib/api";
import { ActionButton, FieldInput, Notice } from "../../components/ui";

export default function JoinPage() {
  const [restaurantName, setRestaurantName] = useState(""); const [locationName, setLocationName] = useState(""); const [address, setAddress] = useState(""); const [ownerName, setOwnerName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [terms, setTerms] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<{tenant_slug:string;location_slug:string;message:string}|null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setError(""); try { const created = await apiClient.post<{tenant_slug:string;location_slug:string;message:string}>("/onboarding/register", { restaurant_name: restaurantName, location_name: locationName, address, owner_name: ownerName, owner_email: email, password, accepted_terms: terms }); setResult(created); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "We could not register the restaurant."); } finally { setPending(false); } }
  return <main className="app-shell"><Link className="wordmark" href="/">CHOWLY<span>°</span></Link><p className="eyebrow">Restaurant registration</p><h1 className="app-title">Bring your<br/><em>restaurant online.</em></h1><p className="subcopy">Create your private Chowly workspace. You can add your menu, tables and team before you publish.</p>{result ? <section className="panel"><Notice tone="success" title="Restaurant workspace created">{result.message}</Notice><p>Sign in with your owner email and password to finish setup.</p><Link className="action action-sun" href="/login">Sign in to continue</Link></section> : <form className="panel" onSubmit={submit}><FieldInput label="Restaurant name" value={restaurantName} onChange={e=>setRestaurantName(e.target.value)} required/><FieldInput label="First location name" value={locationName} onChange={e=>setLocationName(e.target.value)} required/><FieldInput label="Street address" value={address} onChange={e=>setAddress(e.target.value)} required/><FieldInput label="Your name" value={ownerName} onChange={e=>setOwnerName(e.target.value)} required/><FieldInput label="Work email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><FieldInput label="Choose a password" type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required hint="At least 10 characters."/><label><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)} required/> I accept the Chowly terms for this restaurant.</label>{error&&<Notice tone="danger" title="Registration unavailable">{error}</Notice>}<ActionButton type="submit" pending={pending}>Create private workspace</ActionButton></form>}</main>;
}
