"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useRef, useState } from "react";
import { apiClient } from "../../lib/api";
import { Notice, StatusRegion } from "../ui/feedback";
import { ActionButton, Field, FieldInput, SelectInput, TextArea } from "../ui/form-controls";
import { trapDialogTab } from "../ui/dialog";
import { type MenuItem, type PublicMenu, money, saveOrderCapability } from "./contracts";

type CartLine = { item: MenuItem; quantity: number; modifierOptionIds: string[]; specialInstruction: string };
const glyphs = ["✦", "✳", "✹", "✺", "✧", "✶"];
function selectionError(item: MenuItem, selected: string[]) { for (const group of item.modifier_groups) { const n = group.options.filter(o => selected.includes(o.id)).length; if (n < group.minimum_selections || n > group.maximum_selections) return `${group.name}: choose ${group.minimum_selections}–${group.maximum_selections}.`; } return null; }
function lineTotal(line: CartLine) { return (Number(line.item.final_base_price) + line.item.modifier_groups.flatMap(g => g.options).filter(o => line.modifierOptionIds.includes(o.id)).reduce((n, o) => n + Number(o.final_price_delta), 0)) * line.quantity; }
function FoodArt({ item, index }: { item: MenuItem; index: number }) { return <div className={`dish-art ${item.item_type === "DRINK" ? "is-drink" : ""}`} aria-hidden="true"><span>{glyphs[index % glyphs.length]}</span><i /><b /></div>; }

export function DinerMenu({ code }: { code: string }) {
  const router = useRouter();
  const [menu, setMenu] = useState<PublicMenu | null>(null); const [cart, setCart] = useState<CartLine[]>([]); const [active, setActive] = useState<MenuItem | null>(null); const [draft, setDraft] = useState<string[]>([]); const [instruction, setInstruction] = useState(""); const [checkout, setCheckout] = useState(false);
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [mode, setMode] = useState<"DINE_IN" | "TAKEAWAY">("DINE_IN"); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const [created, setCreated] = useState("");
  const detail = useRef<HTMLDialogElement>(null); const checkoutDialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { let alive = true; apiClient.get<PublicMenu>(`/public/tables/${encodeURIComponent(code)}`).then(v => alive && setMenu(v)).catch(r => alive && setError(r instanceof Error ? r.message : "This table QR code is no longer available.")); return () => { alive = false; }; }, [code]);
  useEffect(() => { if (active) detail.current?.showModal(); else detail.current?.close(); }, [active]); useEffect(() => { if (checkout) checkoutDialog.current?.showModal(); else checkoutDialog.current?.close(); }, [checkout]);
  const total = useMemo(() => cart.reduce((n, l) => n + lineTotal(l), 0), [cart]);
  if (error && !menu) return <main className="app-shell"><Notice tone="danger" title="Table unavailable">{error} Ask a waiter for a fresh table QR code.</Notice></main>; if (!menu) return <main className="app-shell"><p className="loading">Opening today’s table menu…</p></main>;
  const open = menu.currently_open && menu.manual_ordering_open; const categories = [...new Map(menu.menu.map(i => [i.category.id, i.category])).values()];
  function openItem(item: MenuItem) { setError(""); setActive(item); setDraft([]); setInstruction(""); }
  function option(id: string, groupId: string) { if (!active) return; const group = active.modifier_groups.find(g => g.id === groupId); if (!group) return; setDraft(now => now.includes(id) ? now.filter(x => x !== id) : [...now.filter(x => !group.options.some(o => o.id === x) || group.maximum_selections !== 1), id]); }
  function add() { if (!active) return; const problem = selectionError(active, draft); if (problem) { setError(problem); return; } setCart(now => [...now, { item: active, quantity: 1, modifierOptionIds: draft, specialInstruction: instruction }]); setActive(null); }
  async function submit() { if (!name.trim() || !phone.trim() || !cart.length) { setError("Add an item, then provide your name and phone number."); return; } setPending(true); setError(""); try { const order = await apiClient.post<{ id: string; access_token: string; realtime_token: string }>(`/public/tables/${encodeURIComponent(code)}/orders`, { customer: { name: name.trim(), phone: phone.trim(), email: email.trim() || null }, service_mode: mode, lines: cart.map(l => ({ menu_item_id: l.item.id, quantity: l.quantity, modifier_option_ids: l.modifierOptionIds, special_instruction: l.specialInstruction || null })) }); saveOrderCapability({ orderId: order.id, accessToken: order.access_token, realtimeToken: order.realtime_token }); setCreated(order.id); setCart([]); router.push(`/order/${order.id}`); } catch (r) { setError(r instanceof Error ? r.message : "Your order was not confirmed. Please try again."); } finally { setPending(false); } }
  return <main className="diner-store"><header className="diner-header"><Link href="/" className="wordmark">CHOWLY<span>°</span></Link><div><b>{menu.location_name}</b><small>{menu.table_label} · Today’s table menu</small></div><button className="cart-trigger" onClick={() => setCheckout(true)} aria-label={`Open order, ${cart.length} items`}>Order <span>{cart.length}</span></button></header><section className="diner-hero"><p className="eyebrow">Table service, made easy</p><h1>Pick a plate.<br /><em>Make it yours.</em></h1><p>{menu.charge_disclosure} Each guest starts a separate order.</p></section>{!open && <Notice tone="warning" title="Ordering is paused">You can browse, but this location is not accepting orders now.</Notice>}<nav className="menu-categories" aria-label="Menu categories"><a href="#all">All</a>{categories.map(c => <a key={c.id} href={`#category-${c.id}`}>{c.name}</a>)}</nav><section id="all" className="diner-menu-list">{categories.map(category => <section id={`category-${category.id}`} key={category.id} className="menu-category"><div className="category-heading"><p className="eyebrow">{category.name}</p><h2>{category.name}</h2></div><div className="store-card-grid">{menu.menu.filter(item => item.category.id === category.id).map((item, index) => <article key={item.id} className={`store-card ${item.item_type === "DRINK" ? "drink-card" : ""}`}><button className="store-card-hit" onClick={() => openItem(item)} disabled={!item.available} aria-label={`View ${item.name}`}><FoodArt item={item} index={index} /><span className="card-copy"><small>{item.item_type === "DRINK" ? "From the bar" : "From the kitchen"}</small><b>{item.name}</b><span>{item.description || "Made fresh to order."}</span><strong>{money(item.final_base_price, menu.currency)}</strong></span>{!item.available && <em>Sold out</em>}</button><button className="card-add" disabled={!open || !item.available} onClick={() => openItem(item)}>Add <span>+</span></button></article>)}</div></section>)}</section>
    <dialog className="product-dialog" ref={detail} onClose={() => setActive(null)} onKeyDown={trapDialogTab} aria-labelledby="diner-item-dialog-title" aria-describedby="diner-item-dialog-description">{active && <><button className="dialog-close" onClick={() => setActive(null)} aria-label="Close item details">×</button><FoodArt item={active} index={0} /><p className="eyebrow">{active.category.name}</p><h2 id="diner-item-dialog-title">{active.name}</h2><p id="diner-item-dialog-description">{active.description || "Made fresh to order."}</p><b className="dialog-price">{money(active.final_base_price, menu.currency)}</b>{active.modifier_groups.map(g => <fieldset key={g.id}><legend>{g.name} {g.minimum_selections ? `· choose ${g.minimum_selections}` : "· optional"}</legend>{g.options.map(o => <label key={o.id}><input type={g.maximum_selections === 1 ? "radio" : "checkbox"} checked={draft.includes(o.id)} disabled={!o.available} onChange={() => option(o.id, g.id)} />{o.name}<span>{Number(o.final_price_delta) ? `+${money(o.final_price_delta, menu.currency)}` : ""}</span></label>)}</fieldset>)}<Field label="Kitchen note" hint="Optional preparation guidance only.">{({ id, describedBy }) => <TextArea id={id} aria-describedby={describedBy} value={instruction} onChange={e => setInstruction(e.target.value)} maxLength={400} />}</Field>{error && <p className="error" role="alert">{error}</p>}<ActionButton tone="sun" disabled={!open || !active.available} onClick={add}>Add to this order · {money(active.final_base_price, menu.currency)}</ActionButton></>}</dialog>
    <dialog className="checkout-dialog" ref={checkoutDialog} onClose={() => setCheckout(false)} onKeyDown={trapDialogTab} aria-labelledby="diner-checkout-dialog-title" aria-describedby="diner-checkout-dialog-description"><div className="checkout-head"><div><p className="eyebrow" id="diner-checkout-dialog-description">Your separate order</p><h2 id="diner-checkout-dialog-title">Ready when you are.</h2></div><button className="dialog-close" onClick={() => setCheckout(false)} aria-label="Close order">×</button></div>{cart.length ? <ul className="checkout-lines">{cart.map((l, i) => <li key={`${l.item.id}-${i}`}><span><b>{l.quantity} × {l.item.name}</b>{l.specialInstruction && <small>{l.specialInstruction}</small>}</span><b>{money(lineTotal(l), menu.currency)}</b><button onClick={() => setCart(v => v.filter((_, n) => n !== i))}>Remove</button></li>)}</ul> : <p className="cart-empty">Your order is waiting for a favourite.</p>}<label className="form-label" htmlFor="service-mode">Service</label><SelectInput id="service-mode" value={mode} onChange={e => setMode(e.target.value as "DINE_IN" | "TAKEAWAY")}><option value="DINE_IN">Dine in · {menu.table_label}</option><option value="TAKEAWAY">Switch to takeaway</option></SelectInput><FieldInput label="Your name" autoComplete="name" value={name} onChange={e => setName(e.target.value)} required /><FieldInput label="Phone number" type="tel" inputMode="tel" autoComplete="tel" value={phone} onChange={e => setPhone(e.target.value)} required hint="No account or sign-in is created." /><FieldInput label="Email" type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} optional hint="Optional receipt delivery." /><div className="checkout-total"><span>Total</span><b>{money(total, menu.currency)}</b></div><StatusRegion>{error && <p className="error">{error}</p>}{created && <Notice tone="success" title="Order received"><Link href={`/order/${created}`}>Track your order securely →</Link></Notice>}</StatusRegion><ActionButton tone="sun" pending={pending} disabled={!open || !cart.length} onClick={submit}>Send for staff acceptance</ActionButton></dialog></main>;
}
