"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { apiClient } from "../../lib/api";
import { useConnectivity } from "../../lib/offline/connectivity";
import { publicOrderRealtimeUrl, RealtimeClient, type RealtimeState } from "../../lib/realtime";
import { Notice, StatusRegion } from "../ui/feedback";
import { ActionButton, FieldInput, FieldTextArea } from "../ui/form-controls";
import { loadOrderCapability, money, newIdempotencyKey, type PublicOrder } from "./contracts";

type Receipt = { receipt_number: string; issued_at: string; refunded: boolean; delivery_status: string; payload: Record<string, unknown>; html: string };
type Rating = { id: string; complaint_prompt: boolean; complaint_prompt_message?: string | null };
const statusCopy: Record<string, { title: string; text: string }> = {
  SUBMITTED: { title: "Order sent.", text: "Your service team is checking it now." }, PREPARING: { title: "The good part is underway.", text: "Your kitchen and bar lines are being prepared." }, READY_FOR_SERVICE: { title: "Ready for service.", text: "Your waiter is bringing this to your table." }, SERVED: { title: "Served with care.", text: "When you are ready to leave, pay here." }, PAID: { title: "All settled.", text: "Thank you for dining with us." }, CANCELLED: { title: "This order was cancelled.", text: "Please ask your waiter if you need help." },
};

function capabilityHeaders(orderId: string) {
  const capability = loadOrderCapability(orderId); return capability ? { "X-Order-Access-Token": capability.accessToken } : null;
}

export function DinerOrderJourney({ orderId }: { orderId: string }) {
  const { online } = useConnectivity();
  const [order, setOrder] = useState<PublicOrder | null>(null); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [realtime, setRealtime] = useState<RealtimeState>("connecting");
  const [paymentPending, setPaymentPending] = useState(false); const [receipt, setReceipt] = useState<Receipt | null>(null); const [ratingIds, setRatingIds] = useState<Record<string, string>>({}); const [ratingComments, setRatingComments] = useState<Record<string, string>>({}); const [complaintFor, setComplaintFor] = useState<string | null>(null); const [complaintSubject, setComplaintSubject] = useState(""); const [complaintDetail, setComplaintDetail] = useState("");
  const capability = loadOrderCapability(orderId);
  const load = useCallback(async () => {
    const headers = capabilityHeaders(orderId); if (!headers) { setError("This order link needs its secure browser session. Reopen it from the device used to order or ask your waiter for help."); return; }
    try { const value = await apiClient.get<PublicOrder>(`/public/orders/${encodeURIComponent(orderId)}`, { headers }); setOrder(value); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "We could not refresh this order."); }
  }, [orderId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    if (!capability?.accessToken) return;
    const live = new RealtimeClient({ url: publicOrderRealtimeUrl({ orderId, accessToken: capability.realtimeToken || capability.accessToken }), onEvent: () => void load(), onGap: () => load(), pollSnapshot: load, onStateChange: setRealtime }); live.start(); return () => live.stop();
  }, [capability?.accessToken, capability?.realtimeToken, load, orderId]);
  async function mutate(path: string, body: Record<string, unknown>, success: string) {
    const headers = capabilityHeaders(orderId); if (!headers || !online) { setError("This change needs a live connection and was not sent."); return; }
    try { const result = await apiClient.patch<PublicOrder>(path, body, { headers }); setOrder(result); setNotice(success); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "The change was not confirmed."); }
  }
  async function cancel() { if (!order) return; const reason = window.prompt("Why are you cancelling?", "Cancelled by diner") || "Cancelled by diner"; const headers = capabilityHeaders(orderId); if (!headers || !online) { setError("Cancellation needs a live connection and was not sent."); return; } try { const result = await apiClient.post<PublicOrder>(`/public/orders/${orderId}/cancel`, { expected_version: order.version, reason }, { headers }); setOrder(result); setNotice("Your cancellation was confirmed."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Cancellation was not confirmed."); } }
  async function pay(method: "CARD" | "TRANSFER" | "WALLET", scenario: "APPROVED" | "DECLINED" | "TEMPORARY_FAILURE" = "APPROVED") {
    if (!order || !online) { setError("Payment requires a live connection and was not started."); return; } const headers = capabilityHeaders(orderId); if (!headers) return;
    setPaymentPending(true); try { const result = await apiClient.post<{ status: string; failure_reason?: string }>(`/public/orders/${orderId}/payments`, { method, amount: order.total_amount, currency: order.currency, mock_scenario: scenario }, { headers: { ...headers, "Idempotency-Key": newIdempotencyKey() } }); if (result.status === "SUCCESSFUL") { setNotice("Mock payment confirmed. Your receipt is ready."); await loadReceipt(); await load(); } else setError(result.failure_reason || "Payment was not approved. You can safely retry."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Payment was not confirmed. Do not retry until this page refreshes."); } finally { setPaymentPending(false); }
  }
  async function loadReceipt() { const headers = capabilityHeaders(orderId); if (!headers) return; try { setReceipt(await apiClient.get<Receipt>(`/public/orders/${orderId}/receipt`, { headers })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Your receipt is being prepared. Please refresh shortly."); } }
  async function rate(kind: "order" | "item", score: number, lineId?: string) { const headers = capabilityHeaders(orderId); if (!headers || !online) { setError("Ratings need a live connection and were not sent."); return; } try { const key = lineId || "order"; const comment = ratingComments[key]?.trim() || null; const body = kind === "item" ? { order_line_id: lineId, score, comment } : { score, comment }; const rating = await apiClient.post<Rating>(`/public/orders/${orderId}/ratings/${kind === "item" ? "items" : "order"}`, body, { headers }); setRatingIds((current) => ({ ...current, [key]: rating.id })); if (rating.complaint_prompt) { setComplaintFor(rating.id); setNotice(rating.complaint_prompt_message || "Would you like to tell a manager what went wrong?"); } else setNotice("Thank you for your rating."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Your rating was not saved."); } }
  async function complain() { const headers = capabilityHeaders(orderId); if (!headers || !complaintFor || !complaintSubject.trim() || !complaintDetail.trim()) return; try { const payload: Record<string, string> = { subject: complaintSubject.trim(), detail: complaintDetail.trim() }; const lineRating = Object.entries(ratingIds).find(([, id]) => id === complaintFor); if (lineRating?.[0] === "order") payload.order_rating_id = complaintFor; else payload.item_rating_id = complaintFor; await apiClient.post(`/public/orders/${orderId}/complaints`, payload, { headers }); setNotice("Your complaint was sent privately to the manager."); setComplaintFor(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Your complaint was not sent."); } }
  if (!capability) return <main className="app-shell"><Notice tone="warning" title="Secure order link unavailable">This device does not hold the private order capability. For privacy, Chowly cannot display an order from a guessed ID.</Notice></main>;
  if (!order) return <main className="app-shell"><p className="loading">Finding your secure order…</p><StatusRegion>{error && <Notice tone="danger">{error}</Notice>}</StatusRegion></main>;
  const shownStatus = order.diner_status || order.status; const detail = statusCopy[shownStatus] || statusCopy.SUBMITTED; const isUnaccepted = shownStatus === "SUBMITTED";
  return <main className="app-shell"><header className="app-top"><Link href="/" className="wordmark">CHOWLY<span>°</span></Link><div className="meta">Order {order.id.slice(0, 8).toUpperCase()}<br /><b>{order.table_label || "Takeaway"}</b></div></header><section className="order-state"><p className="eyebrow">{shownStatus.replaceAll("_", " ")} · {realtime === "live" ? "live" : realtime}</p><h1 className="app-title">{detail.title}</h1><p className="subcopy">{detail.text}</p>{!online && <Notice tone="warning" title="You are offline">You can keep this status page open, but payment, cancellation, and service changes wait for a live connection.</Notice>}{order.transfer_notice && <Notice tone="info" title="Table update">{order.transfer_notice}</Notice>}{order.cancellation_reason && <Notice tone="info" title="Cancellation reason">{order.cancellation_reason}</Notice>}{order.estimated_wait_minutes && shownStatus === "PREPARING" && <p className="wait-note">Estimated wait · <b>{order.estimated_wait_minutes} minutes</b></p>}<ul className="cart-list">{order.lines.map((line) => <li key={line.id}><span>{line.quantity} × {line.item_name}{line.modifiers.length ? ` · ${line.modifiers.map((item) => item.name).join(", ")}` : ""}</span><b>{money(line.total_amount, order.currency)}</b></li>)}</ul><div className="receipt-total"><span>Order total</span><b>{money(order.total_amount, order.currency)}</b></div>
    {isUnaccepted && <div className="payment-actions"><ActionButton tone="quiet" disabled={!online || order.service_mode === "TAKEAWAY"} onClick={() => mutate(`/public/orders/${orderId}/service-mode`, { service_mode: "TAKEAWAY", expected_version: order.version }, "Switched to takeaway.")}>Switch to takeaway</ActionButton><ActionButton tone="danger" disabled={!online} onClick={cancel}>Cancel before acceptance</ActionButton></div>}
    {shownStatus === "SERVED" && <div className="payment-actions"><p className="form-label">Mock payment · one full payment only</p><ActionButton pending={paymentPending} onClick={() => pay("CARD")}>Pay by card</ActionButton><ActionButton tone="quiet" pending={paymentPending} onClick={() => pay("TRANSFER")}>Bank transfer</ActionButton><ActionButton tone="quiet" pending={paymentPending} onClick={() => pay("WALLET")}>Wallet</ActionButton><button type="button" onClick={() => pay("CARD", "DECLINED")}>Test declined retry</button></div>}
    {(shownStatus === "PAID" || receipt) && <div className="panel"><h2>Digital receipt</h2><ActionButton tone="quiet" onClick={loadReceipt}>Refresh receipt</ActionButton>{receipt && <><p>Receipt {receipt.receipt_number} · {receipt.refunded ? "Refunded" : "Paid"} · delivery {receipt.delivery_status.toLowerCase()}</p><details><summary>View receipt details</summary><pre>{JSON.stringify(receipt.payload, null, 2)}</pre></details></>}</div>}
    {(shownStatus === "SERVED" || shownStatus === "PAID") && <section className="panel"><h2>How was it?</h2>{order.lines.map((line) => <div key={line.id}><p>{line.item_name}</p><FieldInput label={`Optional note about ${line.item_name}`} optional value={ratingComments[line.id] || ""} onChange={(event) => setRatingComments((current) => ({ ...current, [line.id]: event.target.value }))} />{[1, 2, 3, 4, 5].map((score) => <button key={score} type="button" disabled={Boolean(ratingIds[line.id])} aria-label={`Rate ${line.item_name} ${score} out of 5`} onClick={() => rate("item", score, line.id)}>{score}★</button>)}</div>)}<p>Overall experience</p><FieldTextArea label="Optional overall comment" optional value={ratingComments.order || ""} onChange={(event) => setRatingComments((current) => ({ ...current, order: event.target.value }))} />{[1, 2, 3, 4, 5].map((score) => <button key={score} type="button" disabled={Boolean(ratingIds.order)} aria-label={`Rate overall order ${score} out of 5`} onClick={() => rate("order", score)}>{score}★</button>)}{complaintFor && <div><FieldInput label="What went wrong?" value={complaintSubject} onChange={(event) => setComplaintSubject(event.target.value)} /><FieldTextArea label="Tell the manager privately" value={complaintDetail} onChange={(event) => setComplaintDetail(event.target.value)} /><ActionButton tone="danger" onClick={complain}>Send private complaint</ActionButton><button type="button" onClick={() => setComplaintFor(null)}>No thanks</button></div>}</section>}
    <StatusRegion>{notice && <Notice tone="success">{notice}</Notice>}{error && <Notice tone="danger">{error}</Notice>}</StatusRegion></section></main>;
}
