"""initial Chowly V1 schema

Revision ID: 48f961b063ff
Revises: 
Create Date: 2026-08-30 23:51:41.936665
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '48f961b063ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('retention_days', sa.Integer(), server_default='90', nullable=False),
    sa.Column('retention_extension_requested_days', sa.Integer(), nullable=True),
    sa.Column('retention_extension_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_extension_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_extension_approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('retention_days <= 120 OR retention_extension_approved_at IS NOT NULL', name=op.f('ck_tenants_ck_tenant_retention_extension_approved')),
    sa.CheckConstraint('retention_days >= 1', name=op.f('ck_tenants_ck_tenant_retention_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('name', name=op.f('uq_tenants_name'))
    )
    op.create_table('customer_tenant_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('phone_snapshot', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_tenant_records_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_customer_tenant_records_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_tenant_records')),
    sa.UniqueConstraint('tenant_id', 'customer_id', 'id', name='uq_customer_tenant_record_customer_scope'),
    sa.UniqueConstraint('tenant_id', 'customer_id', name='uq_customer_tenant_visibility'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_customer_tenant_record_scope_id')
    )
    op.create_index(op.f('ix_customer_tenant_records_purge_after'), 'customer_tenant_records', ['purge_after'], unique=False)
    op.create_index(op.f('ix_customer_tenant_records_tenant_id'), 'customer_tenant_records', ['tenant_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NGN', nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=7, scale=6), server_default='0.075', nullable=False),
    sa.Column('service_charge_rate', sa.Numeric(precision=7, scale=6), server_default='0', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Africa/Lagos', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('is_open', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('service_charge_rate >= 0 AND service_charge_rate <= 1', name=op.f('ck_locations_ck_location_service_charge_rate')),
    sa.CheckConstraint('vat_rate >= 0 AND vat_rate <= 1', name=op.f('ck_locations_ck_location_vat_rate')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_locations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_location_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_location_tenant_name')
    )
    op.create_index(op.f('ix_locations_tenant_id'), 'locations', ['tenant_id'], unique=False)
    op.create_table('dining_tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('daily_code', sa.String(length=80), nullable=True),
    sa.Column('code_issued_on', sa.String(length=10), nullable=True),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_dining_tables_ck_dining_table_capacity')),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id'], ['locations.tenant_id', 'locations.id'], name='fk_dining_table_location', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dining_tables')),
    sa.UniqueConstraint('tenant_id', 'location_id', 'id', name='uq_dining_table_scope_id'),
    sa.UniqueConstraint('tenant_id', 'location_id', 'label', name='uq_dining_table_label')
    )
    op.create_index(op.f('ix_dining_tables_daily_code'), 'dining_tables', ['daily_code'], unique=True)
    op.create_index(op.f('ix_dining_tables_location_id'), 'dining_tables', ['location_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('item_type', sa.Enum('FOOD', 'DRINK', name='menu_item_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('sold_out_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_out_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('base_price >= 0', name=op.f('ck_menu_items_ck_menu_item_price_nonnegative')),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id'], ['locations.tenant_id', 'locations.id'], name='fk_menu_item_location', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_items')),
    sa.UniqueConstraint('tenant_id', 'location_id', 'id', name='uq_menu_item_scope_id')
    )
    op.create_index(op.f('ix_menu_items_location_id'), 'menu_items', ['location_id'], unique=False)
    op.create_table('operating_hours',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.CheckConstraint('is_closed = true OR (opens_at IS NOT NULL AND closes_at IS NOT NULL)', name=op.f('ck_operating_hours_ck_operating_hour_times_when_open')),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_operating_hours_ck_operating_hour_weekday')),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id'], ['locations.tenant_id', 'locations.id'], name='fk_operating_hour_location', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operating_hours')),
    sa.UniqueConstraint('tenant_id', 'location_id', 'weekday', name='uq_operating_hour_day')
    )
    op.create_table('staff_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('invitation_status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitation_status', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('invitation_token_hash', sa.String(length=64), nullable=True),
    sa.Column('invitation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by_id', sa.String(length=36), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_platform_admin', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['staff_accounts.id'], name=op.f('fk_staff_accounts_invited_by_id_staff_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_staff_accounts_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_staff_accounts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_accounts')),
    sa.UniqueConstraint('email', name='uq_staff_account_email'),
    sa.UniqueConstraint('invitation_token_hash', name=op.f('uq_staff_accounts_invitation_token_hash')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_staff_account_tenant_id')
    )
    op.create_index(op.f('ix_staff_accounts_location_id'), 'staff_accounts', ['location_id'], unique=False)
    op.create_index(op.f('ix_staff_accounts_tenant_id'), 'staff_accounts', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('subject_type', sa.String(length=60), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'actor_id'], ['staff_accounts.tenant_id', 'staff_accounts.id'], name='fk_audit_event_actor'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id'], ['locations.tenant_id', 'locations.id'], name='fk_audit_event_location'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_location_id'), 'audit_events', ['location_id'], unique=False)
    op.create_index('ix_audit_subject', 'audit_events', ['tenant_id', 'location_id', 'subject_type', 'subject_id', 'created_at'], unique=False)
    op.create_table('modifier_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('minimum_selections', sa.Integer(), server_default='0', nullable=False),
    sa.Column('maximum_selections', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('maximum_selections >= minimum_selections', name=op.f('ck_modifier_groups_ck_modifier_group_max')),
    sa.CheckConstraint('minimum_selections >= 0', name=op.f('ck_modifier_groups_ck_modifier_group_min')),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'menu_item_id'], ['menu_items.tenant_id', 'menu_items.location_id', 'menu_items.id'], name='fk_modifier_group_menu_item', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modifier_groups')),
    sa.UniqueConstraint('tenant_id', 'location_id', 'menu_item_id', 'name', name='uq_modifier_group_name')
    )
    op.create_index(op.f('ix_modifier_groups_menu_item_id'), 'modifier_groups', ['menu_item_id'], unique=False)
    op.create_table('staff_location_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['staff_accounts.id'], name=op.f('fk_staff_location_assignments_assigned_by_id_staff_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id'], ['locations.tenant_id', 'locations.id'], name='fk_staff_location_location', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'staff_id'], ['staff_accounts.tenant_id', 'staff_accounts.id'], name='fk_staff_location_account', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_location_assignments')),
    sa.UniqueConstraint('tenant_id', 'location_id', 'staff_id', name='uq_staff_location')
    )
    op.create_table('staff_role_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('PLATFORM_ADMIN', 'TENANT_OWNER', 'MANAGER', 'WAITER', 'CHEF', 'BARTENDER', name='staff_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('granted_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['staff_accounts.id'], name=op.f('fk_staff_role_assignments_granted_by_id_staff_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'staff_id'], ['staff_accounts.tenant_id', 'staff_accounts.id'], name='fk_staff_role_account', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_role_assignments')),
    sa.UniqueConstraint('tenant_id', 'staff_id', 'role', name='uq_staff_role')
    )
    op.create_table('table_visits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_by_order_id', sa.String(length=36), nullable=True),
    sa.Column('closed_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['staff_accounts.id'], name=op.f('fk_table_visits_closed_by_id_staff_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'table_id'], ['dining_tables.tenant_id', 'dining_tables.location_id', 'dining_tables.id'], name='fk_table_visit_table', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_table_visits')),
    sa.UniqueConstraint('tenant_id', 'location_id', 'id', name='uq_table_visit_scope_id')
    )
    op.create_index(op.f('ix_table_visits_table_id'), 'table_visits', ['table_id'], unique=False)
    op.create_index('uq_table_visit_active', 'table_visits', ['tenant_id', 'location_id', 'table_id'], unique=True, postgresql_where=sa.text('closed_at IS NULL'), sqlite_where=sa.text('closed_at IS NULL'))
    op.create_table('modifier_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_delta', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('available', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('price_delta >= 0', name=op.f('ck_modifier_options_ck_modifier_option_price_nonnegative')),
    sa.ForeignKeyConstraint(['group_id'], ['modifier_groups.id'], name=op.f('fk_modifier_options_group_id_modifier_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'menu_item_id'], ['menu_items.tenant_id', 'menu_items.location_id', 'menu_items.id'], name='fk_modifier_option_menu_item', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modifier_options')),
    sa.UniqueConstraint('tenant_id', 'location_id', 'menu_item_id', 'id', name='uq_modifier_option_scope_id')
    )
    op.create_index(op.f('ix_modifier_options_menu_item_id'), 'modifier_options', ['menu_item_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=True),
    sa.Column('visit_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('customer_tenant_record_id', sa.String(length=36), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('public_access_token_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Enum('QR', 'MANUAL', name='order_source', native_enum=False, create_constraint=True), server_default='QR', nullable=False),
    sa.Column('service_mode', sa.Enum('DINE_IN', 'TAKEAWAY', name='service_mode', native_enum=False, create_constraint=True), server_default='DINE_IN', nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'PREPARING', 'READY_FOR_SERVICE', 'SERVED', 'PAID', 'CANCELLED', name='order_status', native_enum=False, create_constraint=True), server_default='SUBMITTED', nullable=False),
    sa.Column('estimated_wait_minutes', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('transfer_notice', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='NGN', nullable=False),
    sa.Column('vat_rate_snapshot', sa.Numeric(precision=7, scale=6), server_default='0', nullable=False),
    sa.Column('service_charge_rate_snapshot', sa.Numeric(precision=7, scale=6), server_default='0', nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('service_charge_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('served_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('estimated_wait_minutes IS NULL OR estimated_wait_minutes BETWEEN 1 AND 180', name=op.f('ck_orders_ck_order_wait_minutes')),
    sa.CheckConstraint('subtotal_amount >= 0 AND vat_amount >= 0 AND service_charge_amount >= 0 AND total_amount >= 0', name=op.f('ck_orders_ck_order_amounts_nonnegative')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers')),
    sa.ForeignKeyConstraint(['tenant_id', 'customer_id', 'customer_tenant_record_id'], ['customer_tenant_records.tenant_id', 'customer_tenant_records.customer_id', 'customer_tenant_records.id'], name='fk_order_customer_tenant_record'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'owner_id'], ['staff_location_assignments.tenant_id', 'staff_location_assignments.location_id', 'staff_location_assignments.staff_id'], name='fk_order_owner_assignment'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'table_id'], ['dining_tables.tenant_id', 'dining_tables.location_id', 'dining_tables.id'], name='fk_order_table'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'visit_id'], ['table_visits.tenant_id', 'table_visits.location_id', 'table_visits.id'], name='fk_order_visit'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id'], ['locations.tenant_id', 'locations.id'], name='fk_order_location'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('public_access_token_hash', name=op.f('uq_orders_public_access_token_hash')),
    sa.UniqueConstraint('tenant_id', 'location_id', 'id', name='uq_order_scope_id')
    )
    op.create_index('ix_order_active_table', 'orders', ['tenant_id', 'location_id', 'table_id', 'status'], unique=False)
    op.create_index('ix_order_report_created', 'orders', ['tenant_id', 'location_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_location_id'), 'orders', ['location_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('customer_phone', sa.String(length=32), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'SEATED', name='reservation_status', native_enum=False, create_constraint=True), server_default='REQUESTED', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_by_id', sa.String(length=36), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('party_size > 0', name=op.f('ck_reservations_ck_reservation_party_size')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_reservations_customer_id_customers')),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'confirmed_by_id'], ['staff_location_assignments.tenant_id', 'staff_location_assignments.location_id', 'staff_location_assignments.staff_id'], name='fk_reservation_confirmer_assignment'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'table_id'], ['dining_tables.tenant_id', 'dining_tables.location_id', 'dining_tables.id'], name='fk_reservation_table'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id'], ['locations.tenant_id', 'locations.id'], name='fk_reservation_location'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations'))
    )
    op.create_index('ix_reservation_time', 'reservations', ['tenant_id', 'location_id', 'requested_at'], unique=False)
    op.create_table('table_qr_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'generated_by_id'], ['staff_location_assignments.tenant_id', 'staff_location_assignments.location_id', 'staff_location_assignments.staff_id'], name='fk_table_qr_generator_assignment'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'table_id'], ['dining_tables.tenant_id', 'dining_tables.location_id', 'dining_tables.id'], name='fk_table_qr_table', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_table_qr_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_table_qr_tokens_token_hash'))
    )
    op.create_index('ix_table_qr_daily_lookup', 'table_qr_tokens', ['tenant_id', 'location_id', 'table_id', 'issued_on'], unique=False)
    op.create_index('uq_table_qr_active_daily', 'table_qr_tokens', ['tenant_id', 'location_id', 'table_id', 'issued_on'], unique=True, postgresql_where=sa.text('invalidated_at IS NULL'), sqlite_where=sa.text('invalidated_at IS NULL'))
    op.create_table('order_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('claimed_by_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('item_name_snapshot', sa.String(length=160), nullable=False),
    sa.Column('modifiers_snapshot', sa.Text(), server_default='', nullable=False),
    sa.Column('selected_modifiers', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('special_instruction', sa.Text(), nullable=True),
    sa.Column('queue_destination', sa.Enum('KITCHEN', 'BAR', name='queue_destination', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('service_charge_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLAIMED', 'READY', 'CANCELLED', name='line_status', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_lines_ck_order_line_quantity')),
    sa.CheckConstraint('unit_price >= 0 AND subtotal_amount >= 0 AND vat_amount >= 0 AND service_charge_amount >= 0 AND total_amount >= 0', name=op.f('ck_order_lines_ck_order_line_amounts_nonnegative')),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'claimed_by_id'], ['staff_location_assignments.tenant_id', 'staff_location_assignments.location_id', 'staff_location_assignments.staff_id'], name='fk_order_line_claimed_assignment'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'menu_item_id'], ['menu_items.tenant_id', 'menu_items.location_id', 'menu_items.id'], name='fk_order_line_menu_item'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'order_id'], ['orders.tenant_id', 'orders.location_id', 'orders.id'], name='fk_order_line_order', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_lines')),
    sa.UniqueConstraint('tenant_id', 'location_id', 'order_id', 'id', name='uq_order_line_order_scope_id'),
    sa.UniqueConstraint('tenant_id', 'location_id', 'id', name='uq_order_line_scope_id')
    )
    op.create_index('ix_order_line_queue', 'order_lines', ['tenant_id', 'location_id', 'queue_destination', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_table('order_ratings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score BETWEEN 1 AND 5', name=op.f('ck_order_ratings_ck_order_rating_score')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_order_ratings_customer_id_customers')),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'order_id'], ['orders.tenant_id', 'orders.location_id', 'orders.id'], name='fk_order_rating_order', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_ratings')),
    sa.UniqueConstraint('order_id', name='uq_order_rating_order'),
    sa.UniqueConstraint('tenant_id', 'location_id', 'id', name='uq_order_rating_scope_id')
    )
    op.create_table('payment_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.Enum('CARD', 'TRANSFER', 'WALLET', 'CASH', name='payment_method', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NGN', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESSFUL', 'FAILED', name='payment_status', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('provider_code', sa.String(length=80), nullable=True),
    sa.Column('failure_reason', sa.String(length=300), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('recorded_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payment_attempts_ck_payment_attempt_amount_positive')),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'order_id'], ['orders.tenant_id', 'orders.location_id', 'orders.id'], name='fk_payment_attempt_order', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'recorded_by_id'], ['staff_location_assignments.tenant_id', 'staff_location_assignments.location_id', 'staff_location_assignments.staff_id'], name='fk_payment_recorder_assignment'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_attempts')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_payment_attempts_idempotency_key')),
    sa.UniqueConstraint('reference', name=op.f('uq_payment_attempts_reference')),
    sa.UniqueConstraint('tenant_id', 'location_id', 'order_id', 'id', name='uq_payment_attempt_order_scope_id')
    )
    op.create_index(op.f('ix_payment_attempts_order_id'), 'payment_attempts', ['order_id'], unique=False)
    op.create_index('ix_payment_report_created', 'payment_attempts', ['tenant_id', 'location_id', 'created_at'], unique=False)
    op.create_index('uq_payment_successful_order', 'payment_attempts', ['order_id'], unique=True, postgresql_where=sa.text("status = 'SUCCESSFUL'"), sqlite_where=sa.text("status = 'SUCCESSFUL'"))
    op.create_table('receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('receipt_number', sa.String(length=80), nullable=False),
    sa.Column('payload_snapshot', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('email_to', sa.String(length=255), nullable=True),
    sa.Column('delivery_status', sa.Enum('NOT_REQUESTED', 'PENDING', 'SENT', 'FAILED', name='receipt_delivery_status', native_enum=False, create_constraint=True), server_default='NOT_REQUESTED', nullable=False),
    sa.Column('delivery_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'order_id'], ['orders.tenant_id', 'orders.location_id', 'orders.id'], name='fk_receipt_order', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts')),
    sa.UniqueConstraint('order_id', name='uq_receipt_order'),
    sa.UniqueConstraint('receipt_number', name=op.f('uq_receipts_receipt_number'))
    )
    op.create_table('item_ratings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('order_line_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score BETWEEN 1 AND 5', name=op.f('ck_item_ratings_ck_item_rating_score')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_item_ratings_customer_id_customers')),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'order_id'], ['orders.tenant_id', 'orders.location_id', 'orders.id'], name='fk_item_rating_order', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'order_id', 'order_line_id'], ['order_lines.tenant_id', 'order_lines.location_id', 'order_lines.order_id', 'order_lines.id'], name='fk_item_rating_line', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_ratings')),
    sa.UniqueConstraint('order_line_id', name='uq_item_rating_line'),
    sa.UniqueConstraint('tenant_id', 'location_id', 'id', name='uq_item_rating_scope_id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('payment_attempt_id', sa.String(length=36), nullable=False),
    sa.Column('manager_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NGN', nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESSFUL', 'FAILED', name='refund_status', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_refunds_ck_refund_amount_positive')),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'order_id', 'payment_attempt_id'], ['payment_attempts.tenant_id', 'payment_attempts.location_id', 'payment_attempts.order_id', 'payment_attempts.id'], name='fk_refund_payment_attempt'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'manager_id'], ['staff_location_assignments.tenant_id', 'staff_location_assignments.location_id', 'staff_location_assignments.staff_id'], name='fk_refund_manager_assignment'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'order_id'], ['orders.tenant_id', 'orders.location_id', 'orders.id'], name='fk_refund_order', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_refunds_idempotency_key')),
    sa.UniqueConstraint('reference', name=op.f('uq_refunds_reference'))
    )
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_index('uq_refund_successful_order', 'refunds', ['order_id'], unique=True, postgresql_where=sa.text("status = 'SUCCESSFUL'"), sqlite_where=sa.text("status = 'SUCCESSFUL'"))
    op.create_table('complaints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('order_rating_id', sa.String(length=36), nullable=True),
    sa.Column('item_rating_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'DISMISSED', name='complaint_status', native_enum=False, create_constraint=True), server_default='OPEN', nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_complaints_customer_id_customers')),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'item_rating_id'], ['item_ratings.tenant_id', 'item_ratings.location_id', 'item_ratings.id'], name='fk_complaint_item_rating'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'order_rating_id'], ['order_ratings.tenant_id', 'order_ratings.location_id', 'order_ratings.id'], name='fk_complaint_order_rating'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'order_id'], ['orders.tenant_id', 'orders.location_id', 'orders.id'], name='fk_complaint_order', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'location_id', 'resolved_by_id'], ['staff_location_assignments.tenant_id', 'staff_location_assignments.location_id', 'staff_location_assignments.staff_id'], name='fk_complaint_resolver_assignment'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints'))
    )
    op.create_index('ix_complaint_status', 'complaints', ['tenant_id', 'location_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_complaint_status', table_name='complaints')
    op.drop_table('complaints')
    op.drop_index('uq_refund_successful_order', table_name='refunds', postgresql_where=sa.text("status = 'SUCCESSFUL'"), sqlite_where=sa.text("status = 'SUCCESSFUL'"))
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_table('item_ratings')
    op.drop_table('receipts')
    op.drop_index('uq_payment_successful_order', table_name='payment_attempts', postgresql_where=sa.text("status = 'SUCCESSFUL'"), sqlite_where=sa.text("status = 'SUCCESSFUL'"))
    op.drop_index('ix_payment_report_created', table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_order_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_table('order_ratings')
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_index('ix_order_line_queue', table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index('uq_table_qr_active_daily', table_name='table_qr_tokens', postgresql_where=sa.text('invalidated_at IS NULL'), sqlite_where=sa.text('invalidated_at IS NULL'))
    op.drop_index('ix_table_qr_daily_lookup', table_name='table_qr_tokens')
    op.drop_table('table_qr_tokens')
    op.drop_index('ix_reservation_time', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_orders_location_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index('ix_order_report_created', table_name='orders')
    op.drop_index('ix_order_active_table', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_modifier_options_menu_item_id'), table_name='modifier_options')
    op.drop_table('modifier_options')
    op.drop_index('uq_table_visit_active', table_name='table_visits', postgresql_where=sa.text('closed_at IS NULL'), sqlite_where=sa.text('closed_at IS NULL'))
    op.drop_index(op.f('ix_table_visits_table_id'), table_name='table_visits')
    op.drop_table('table_visits')
    op.drop_table('staff_role_assignments')
    op.drop_table('staff_location_assignments')
    op.drop_index(op.f('ix_modifier_groups_menu_item_id'), table_name='modifier_groups')
    op.drop_table('modifier_groups')
    op.drop_index('ix_audit_subject', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_location_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_staff_accounts_tenant_id'), table_name='staff_accounts')
    op.drop_index(op.f('ix_staff_accounts_location_id'), table_name='staff_accounts')
    op.drop_table('staff_accounts')
    op.drop_table('operating_hours')
    op.drop_index(op.f('ix_menu_items_location_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_dining_tables_location_id'), table_name='dining_tables')
    op.drop_index(op.f('ix_dining_tables_daily_code'), table_name='dining_tables')
    op.drop_table('dining_tables')
    op.drop_index(op.f('ix_locations_tenant_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_customer_tenant_records_tenant_id'), table_name='customer_tenant_records')
    op.drop_index(op.f('ix_customer_tenant_records_purge_after'), table_name='customer_tenant_records')
    op.drop_table('customer_tenant_records')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
