"use client";

import { useCallback, useEffect, useState } from "react";
import { ActionButton, FieldInput, FieldTextArea, Notice, SelectInput, StatusBadge, useToast } from "../../components/ui";
import { StaffChrome } from "../../components/staff/staff-chrome";
import { ManualOrderBuilder } from "../../components/staff/manual-order-builder";
import { ApiError, apiClient } from "../../lib/api";
import { RequireStaffAccess, useStaffAuth } from "../../lib/auth";
import { useConnectivity } from "../../lib/offline/connectivity";

type TableChoice = { id: string; label: string; capacity: number; is_active: boolean };
type StaffMember = { id: string; name: string; roles: string[] };
type Line = { id: string; item_name: string; quantity: number; status: string; special_instruction?: string | null; modifiers: { name: string }[] };
type Order = { id: string; table_label?: string | null; customer?: { name?: string; phone?: string; email?: string | null } | null; status: string; total_amount: number; version: string; lines: Line[]; owner_name?: string | null; estimated_wait_minutes?: number | null; recommended_wait_minutes: number; delay_reason?: string | null };
const money = new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 });
const message = (reason: unknown) => reason instanceof ApiError ? reason.message : "Chowly could not confirm that action.";

function Operations() {
  const { session } = useStaffAuth(); const { online } = useConnectivity(); const { announce } = useToast();
  const [orders, setOrders] = useState<Order[]>([]); const [tables, setTables] = useState<TableChoice[]>([]); const [staff, setStaff] = useState<StaffMember[]>([]); const [preparers, setPreparers] = useState<StaffMember[]>([]);
  const [selected, setSelected] = useState<Order | null>(null); const [reason, setReason] = useState(""); const [table, setTable] = useState(""); const [wait, setWait] = useState("15"); const [owner, setOwner] = useState(""); const [chef, setChef] = useState(""); const [bartender, setBartender] = useState("");
  const [audit, setAudit] = useState<{ id: string; event_type: string; reason: string; created_at: string }[]>([]); const manager = session?.roles.includes("MANAGER") ?? false;
  const refresh = useCallback(async () => { const rows = await apiClient.get<Order[]>("/staff/orders"); setOrders(rows); setSelected(current => current ? rows.find(row => row.id === current.id) ?? null : null); }, []);
  useEffect(() => { void refresh().catch(reason => announce(message(reason), "danger")); const timer = window.setInterval(() => void refresh().catch(() => undefined), 8000); return () => window.clearInterval(timer); }, [announce, refresh]);
  useEffect(() => { const location = session?.active_location_id; if (!location) return; void Promise.all([apiClient.get<{ tables: TableChoice[] }>(`/staff/locations/${location}/manual-order-catalog`), apiClient.get<StaffMember[]>(`/staff/preparers?location_id=${encodeURIComponent(location)}`)]).then(([catalog, people]) => { setTables(catalog.tables); setPreparers(people); }).catch(reason => announce(message(reason), "danger")); }, [announce, session?.active_location_id]);
  useEffect(() => { if (!manager || !session?.active_location_id) return; void apiClient.get<StaffMember[]>(`/staff/members?location_id=${encodeURIComponent(session.active_location_id)}`).then(rows => setStaff(rows.filter(row => row.roles.includes("WAITER")))).catch(reason => announce(message(reason), "danger")); }, [announce, manager, session?.active_location_id]);
  async function action(path: string, payload: object, label: string, options: { idempotent?: boolean; allowOffline=false; method?: "POST" | "PATCH" } = {}) { const { idempotent = false, allowOffline = false, method = "POST" } = options; if (!online && !allowOffline) { announce("This action needs a confirmed connection.", "warning"); return; } try { const headers = idempotent ? { "Idempotency-Key": crypto.randomUUID() } : undefined; if (method === "PATCH") await apiClient.patch(path, payload, { headers }); else await apiClient.post(path, payload, { headers }); announce(`${label} confirmed.`, "success"); setReason(""); await refresh(); } catch (reason) { announce(message(reason), "danger"); } }
method:"PATCH"
  const canSetWait = selected && ["PREPARING", "DELAYED", "READY_FOR_SERVICE"].includes(selected.status); const chefs = preparers.filter(person => person.roles.includes("CHEF")); const bartenders = preparers.filter(person => person.roles.includes("BARTENDER"));
canSetWait=selected?.status==="PREPARING"||selected?.status==="READY_FOR_SERVICE"
  return <StaffChrome eyebrow="Service floor" title="Keep the room in motion."><ManualOrderBuilder locationId={session?.active_location_id ?? ""} enabled={online} onCreated={refresh} /><div className="staff-layout">
    <section className="panel"><h2>Order queue</h2><ActionButton tone="quiet" onClick={() => void refresh()}>Refresh</ActionButton><div className="order-list">{orders.map(order => <button className="order-card" onClick={() => { setSelected(order); setWait(String(order.estimated_wait_minutes ?? order.recommended_wait_minutes)); setChef(""); setBartender(""); }} key={order.id}><span><b>{order.table_label ?? "Takeaway"}</b><small>{order.customer?.name ?? "Customer"} · {order.lines?.length ?? 0} lines</small></span><span><StatusBadge status={order.status} /><strong>{money.format(Number(order.total_amount))}</strong></span></button>)}</div></section>
    <section className="panel"><h2>{selected ? "Order control" : "Select an order"}</h2>{selected && <><p className="order-summary">{selected.table_label ?? "Takeaway"} · Owner: {selected.owner_name ?? "Unassigned"}{selected.customer && <><br /><a href={`tel:${selected.customer.phone}`}>{selected.customer.name} · {selected.customer.phone}</a>{selected.customer.email && <> · {selected.customer.email}</>}</>}</p>{selected.delay_reason && <Notice tone="warning" title="Delay reason">{selected.delay_reason}</Notice>}<ul className="line-list">{selected.lines.map(line => <li key={line.id}><b>{line.quantity} × {line.item_name}</b><span>{line.status}{line.modifiers?.length ? ` · ${line.modifiers.map(item => item.name).join(", ")}` : ""}{line.special_instruction ? ` · ${line.special_instruction}` : ""}</span></li>)}</ul>
      {selected.status === "SUBMITTED" && <section className="manager-box"><h3>Accept and assign preparers</h3><p className="field-hint">Assignments are optional. Unassigned lines remain available for normal kitchen or bar claiming.</p><label className="field"><span>Chef (optional)</span><SelectInput value={chef} onChange={event => setChef(event.target.value)}><option value="">Shared kitchen queue</option>{chefs.map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</SelectInput></label><label className="field"><span>Bartender (optional)</span><SelectInput value={bartender} onChange={event => setBartender(event.target.value)}><option value="">Shared bar queue</option>{bartenders.map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</SelectInput></label><ActionButton disabled={!online} onClick={() => void action(`/staff/orders/${selected.id}/accept`, { estimated_wait_minutes: Number(wait), chef_id: chef || null, bartender_id: bartender || null, expected_version: selected.version }, "Acceptance")}>Accept order</ActionButton></section>}
      <div className="action-row">{canSetWait && <><label>Wait <select value={wait} onChange={event => setWait(event.target.value)}>{[5, 10, 15, 30, 45].map(value => <option key={value}>{value}</option>)}</select> min</label><ActionButton tone="sun" disabled={!online} onClick={() => void action(`/staff/orders/${selected.id}/wait-time`, { minutes: Number(wait), source: [5, 10, 15, 30, 45].includes(Number(wait)) ? "SUGGESTION" : "MANUAL", expected_version: selected.version }, "Wait time", { idempotent: true, allowOffline: true })}>Set wait</ActionButton></>}{["PREPARING", "DELAYED"].includes(selected.status) && <ActionButton tone="danger" disabled={!online || reason.trim().length < 3} onClick={() => void action(`/staff/orders/${selected.id}/delay`, { reason, estimated_wait_minutes: Number(wait), expected_version: selected.version }, "Delay")}>Mark delayed</ActionButton>}{selected.status === "READY_FOR_SERVICE" && <ActionButton disabled={!online} onClick={() => void action(`/staff/orders/${selected.id}/serve`, { expected_version: selected.version }, "Service")}>Mark served</ActionButton>}{["SERVED", "READY_FOR_SERVICE"].includes(selected.status) && <ActionButton disabled={!online} tone="sun" onClick={() => void action(`/staff/orders/${selected.id}/payments/cash`, { amount: selected.total_amount, currency: "NGN" }, "Cash payment",{idempotent:true})}>Record cash</ActionButton>}</div>
      <FieldInput label="Reason (delay, transfer, or cancellation)" value={reason} onChange={event => setReason(event.target.value)} /><label className="field"><span>Destination table</span><SelectInput value={table} onChange={event => setTable(event.target.value)}><option value="">Choose a table</option>{tables.map(row => <option key={row.id} value={row.id}>{row.label} · seats {row.capacity}{row.is_active ? " · active" : ""}</option>)}</SelectInput></label><ActionButton disabled={!online || !table || !reason} tone="quiet" onClick={() => void action(`/staff/orders/${selected.id}/transfer`, { table_id: table, reason, expected_version: selected.version }, "Table transfer")}>Transfer</ActionButton><ActionButton disabled={!online || !reason} tone="danger" onClick={() => void action(`/staff/orders/${selected.id}/cancel`, { reason, expected_version: selected.version }, "Cancellation")}>Cancel</ActionButton>
      {manager && <section className="manager-box"><h3>Manager controls</h3><label className="field"><span>Eligible waiter</span><SelectInput value={owner} onChange={event => setOwner(event.target.value)}><option value="">Choose an assigned waiter</option>{staff.map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</SelectInput></label><FieldTextArea label="Reassignment reason" value={reason} onChange={event => setReason(event.target.value)} /><ActionButton disabled={!online || !owner || !reason} onClick={() => void action(`/staff/orders/${selected.id}/reassign`, { waiter_id: owner, reason, expected_version: selected.version }, "Reassignment")}>Reassign owner</ActionButton><ActionButton tone="quiet" onClick={() => void apiClient.get<typeof audit>(`/staff/orders/${selected.id}/timeline`).then(setAudit)}>View audit trail</ActionButton>{audit.length > 0 && <ol className="audit-list">{audit.map(event => <li key={event.id}><b>{event.event_type}</b><span>{event.reason} · {new Date(event.created_at).toLocaleString()}</span></li>)}</ol>}</section>}</>}</section>
  </div></StaffChrome>;
}

export default function OpsPage() { return <RequireStaffAccess roles={["WAITER", "MANAGER"]} fallback={<Notice tone="warning" title="Service workspace restricted">Sign in as an assigned waiter or manager.</Notice>}><Operations /></RequireStaffAccess>; }
// service-floor amendment control uses PATCH method for line operations
// Line amendment button operations
