"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ActionButton, FieldInput, FieldSelect, Notice, StatusBadge } from "../../../components/ui";
import { RequireStaffAccess, useStaffAuth } from "../../../lib/auth";
import { apiClient, ApiError } from "../../../lib/api";
import { StaffChrome } from "../../../components/staff/staff-chrome";

type Category = { id: string; name: string; sort_order: number; is_active: boolean };
type MenuItem = { id: string; name: string; description: string; image_url: string | null; category: Category; item_type: "FOOD" | "DRINK"; queue_destination: "KITCHEN" | "BAR"; final_base_price: number; available: boolean; modifier_groups: unknown[] };
const naira = new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN" });
const message = (reason: unknown) => reason instanceof ApiError ? reason.message : "Chowly could not confirm that action.";

export default function MenuWorkspace() { return <RequireStaffAccess roles={["MANAGER", "TENANT_OWNER", "CHEF", "BARTENDER"]}><MenuPage /></RequireStaffAccess>; }

function MenuPage() {
  const { session } = useStaffAuth(); const locationId = session?.active_location_id ?? "";
  const [categories, setCategories] = useState<Category[]>([]); const [items, setItems] = useState<MenuItem[]>([]); const [kind, setKind] = useState<"ALL" | "FOOD" | "DRINK">("ALL");
  const [categoryId, setCategoryId] = useState(""); const [newCategory, setNewCategory] = useState(""); const [name, setName] = useState(""); const [price, setPrice] = useState(""); const [itemType, setItemType] = useState<"FOOD" | "DRINK">("FOOD"); const [notice, setNotice] = useState(""); const [pending, setPending] = useState(false);
  const canCreateCategory = session?.roles.some((role) => ["MANAGER", "TENANT_OWNER"].includes(role)) ?? false;
  const privilegedMenuEditor = canCreateCategory;
  const chef = session?.roles.includes("CHEF") ?? false;
  const bartender = session?.roles.includes("BARTENDER") ?? false;
  const stationItemType = privilegedMenuEditor || chef === bartender ? null : chef ? "FOOD" : "DRINK";
  const load = useCallback(async () => { if (!locationId) return; const [categoryRows, itemRows] = await Promise.all([apiClient.get<Category[]>(`/staff/locations/${encodeURIComponent(locationId)}/menu/categories`), apiClient.get<MenuItem[]>(`/staff/locations/${encodeURIComponent(locationId)}/menu/items`)]); setCategories(categoryRows); setItems(itemRows); }, [locationId]);
  useEffect(() => { void load().catch((reason) => setNotice(message(reason))); }, [load]);
  useEffect(() => { if (stationItemType) { setKind(stationItemType); setItemType(stationItemType); } }, [stationItemType]);
  const visible = useMemo(() => items.filter((item) => (!stationItemType || item.item_type===stationItemType) && (kind === "ALL" || item.item_type === kind)), [items, kind, stationItemType]);
  const menuFilters: Array<"ALL" | "FOOD" | "DRINK"> = stationItemType ? [stationItemType] : ["ALL", "FOOD", "DRINK"];
  async function createCategory(event: FormEvent) { event.preventDefault(); setPending(true); try { const row = await apiClient.post<Category>(`/staff/locations/${encodeURIComponent(locationId)}/menu/categories`, { name: newCategory.trim(), sort_order: categories.length }); setNewCategory(""); setCategoryId(row.id); await load(); setNotice("Category added."); } catch (reason) { setNotice(message(reason)); } finally { setPending(false); } }
  async function createItem(event: FormEvent) { event.preventDefault(); const finalItemType=stationItemType??itemType; setPending(true); try { await apiClient.post(`/staff/locations/${encodeURIComponent(locationId)}/menu/items`, { name: name.trim(), description: "", category_id: categoryId, item_type: finalItemType, queue_destination: finalItemType === "FOOD" ? "KITCHEN" : "BAR", base_price: Number(price), available: true }); setName(""); setPrice(""); await load(); setNotice("Menu item added."); } catch (reason) { setNotice(message(reason)); } finally { setPending(false); } }
  async function availability(item: MenuItem) { if(stationItemType&&item.item_type!==stationItemType){setNotice("You can only change availability for your preparation station.");return;} setPending(true); try { await apiClient.post(`/staff/locations/${encodeURIComponent(locationId)}/menu/items/${encodeURIComponent(item.id)}/sold-out`, { sold_out: item.available, reason: item.available ? "Temporarily unavailable" : null }); await load(); setNotice(item.available ? "Marked sold out." : "Made available."); } catch (reason) { setNotice(message(reason)); } finally { setPending(false); } }
  return <StaffChrome eyebrow="Menu studio" title="Publish what guests can order.">
    {notice && <Notice tone={notice.includes("added") || notice.includes("available") ? "success" : "danger"} title="Menu">{notice}</Notice>}
    <section className="admin-grid">{canCreateCategory && <form className="panel" onSubmit={createCategory}><p className="eyebrow">Structure</p><h2>Add a category</h2><FieldInput label="Category name" value={newCategory} onChange={(event) => setNewCategory(event.target.value)} placeholder="Grills, Cocktails, Sides…" required /><ActionButton type="submit" pending={pending}>Add category</ActionButton></form>}<form className="panel" onSubmit={createItem}><p className="eyebrow">New card</p><h2>Add a menu item</h2><FieldSelect label="Category" value={categoryId} onChange={(event) => setCategoryId(event.target.value)} required><option value="">Choose a category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</FieldSelect><FieldInput label="Name" value={name} onChange={(event) => setName(event.target.value)} required /><FieldInput label="Base price (NGN)" type="number" min="0" step="0.01" value={price} onChange={(event) => setPrice(event.target.value)} required />{stationItemType?<p className="field-hint">This role can publish {stationItemType==="FOOD"?"Food · kitchen":"Drink · bar"} menu cards only.</p>:<FieldSelect label="Menu type" value={itemType} onChange={(event) => setItemType(event.target.value as "FOOD" | "DRINK")}><option value="FOOD">Food · kitchen</option><option value="DRINK">Drink · bar</option></FieldSelect>}<ActionButton type="submit" pending={pending} disabled={!categoryId}>Add menu card</ActionButton></form></section>
    <section className="panel menu-workspace"><div className="panel-heading"><div><p className="eyebrow">Published inventory</p><h2>{stationItemType==="FOOD"?"Kitchen menu":stationItemType==="DRINK"?"Bar menu":"Food & drinks"}</h2></div><div className="segmented-control" aria-label="Menu type filter">{menuFilters.map((value) => <button key={value} type="button" className={kind === value ? "is-selected" : ""} onClick={() => setKind(value)}>{value === "ALL" ? "All" : value === "FOOD" ? "Food" : "Drinks"}</button>)}</div></div><div className="store-card-grid">{visible.map((item, index) => <article className={`store-card ${item.item_type === "DRINK" ? "drink-card" : ""}`} key={item.id}><div className="dish-art" aria-hidden="true"><span>{item.item_type === "DRINK" ? "✦" : ["✳", "✹", "✺"][index % 3]}</span><i /><b /></div><div className="card-copy"><small>{item.category.name} · {item.item_type === "DRINK" ? "bar" : "kitchen"}</small><b>{item.name}</b><span>{item.description || "No description yet."}</span><strong>{naira.format(Number(item.final_base_price))}</strong></div><div className="card-admin"><StatusBadge status={item.available ? "AVAILABLE" : "SOLD_OUT"} /><ActionButton tone={item.available ? "danger" : "sun"} pending={pending} onClick={() => void availability(item)}>{item.available ? "Mark sold out" : "Make available"}</ActionButton></div></article>)}</div>{visible.length === 0 && <p className="loading">No matching menu cards yet.</p>}</section>
  </StaffChrome>;
}
